---
title: "Estimando el modelo de gravedad estructural con una regresión Pseudo Máxima Verosimilitud de Poisson"
description: "¿Cuáles han sido los patrones comerciales de Guatemala desde 1995 hasta 2020 cuando se considera en el análisis a sus socios de comercio exterior en América?"
categories: [Comercio internacional, Econometría, Datos de panel]
date: "6/6/2022"
---

## El plan

El principal propósito de esta entrada es demostrar cómo estimar en R un modelo de gravedad a partir de una regresión Pseudo Máxima Verosimilitud de Poisson (PPML, por sus siglas en inglés). ¿Porqué PPML? Bueno, existe una gran cantidad de estudios en la literatura que indican que este es uno de los métodos más congruentes con la teoría gravitacional del comercio exterior, un modelo que en su forma más sencilla describe al volumen de los flujos de intercambio comercial bilateral entre países por medio de una función que es proporcional al tamaño de sus economías e inversamente proporcional a la distancia geográfica que existe entre ellas[^1].

[^1]: Si esto suena familiar, quizás sea porque el modelo de gravedad del comercio es una analogía de la Ley de Gravitación Universal de Newton, pero aplicada al análisis de los flujos de comercio bilateral entre países.

Sin embargo, la teoría del comercio es un tema apasionante; los datos brindan muchas oportunidades para hacer todo tipo de análisis. Por eso, antes de estimar al modelo, tomaremos el tiempo para hacer dos cosas:

-   Un repaso por los puntos claves de la teoría del comercio que no solo nos ayudará a interpretar los resultados de la estimación, sino que tendrá una influencia en la especificación de nuestro modelo gravitacional.

-   Un análisis de datos que será la excusa perfecta para mostrar como aprovechar muchas de las funciones que los paquetes incluidos en el `tidyverse` nos ofrecen para manipular y visualizar nuestros datos.

Ese es el plan. Manos a la obra.
