project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Fuentes"
  favicon: favicon.png
  site-url: https://gafnts.github.io/
  twitter-card: true
    card-style: summary_large_image
    creator: "@gafnts"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-SLRQS7H2TD"
    anonymize-ip: true
  lang: es
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: logo.png
    left:
      - text: Sobre mí
        href: about.qmd
      - text: Blog
        href: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/gafnts
      - icon: github
        href: https://github.com/gafnts
  page-footer: 
      left: "© Gabriel Fuentes (2022)" 
      right: 
        - icon: github
          href: https://github.com/gafnts
        - icon: twitter 
          href: https://twitter.com/gants
      border: true
      background: dark
            
format:
  html:
    theme: dark.scss
    css: styles.css
    
editor: visual

