project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Fuentes"
  lang: es
  navbar:
    left:
      - text: Sobre mí
        href: about.qmd
      - text: Blog
        href: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/gafnts
      - icon: github
        href: https://github.com/gafnts
format:
  html:
    theme: 
      dark: dark.scss
      light: flatly
    css: styles.css

editor: visual

