project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Fuentes"
  lang: es
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gafnts
      - icon: twitter
        href: https://twitter.com/gafnts
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

